# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='id',
            new_name='cid',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='id',
            new_name='cid',
        ),
    ]
