# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0002_auto_20180322_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='interface_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='link_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='topology',
            old_name='topology_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='topologyinventory',
            old_name='topology_inventory_id',
            new_name='id',
        ),
    ]
