# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0003_auto_20180323_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='host_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Host'),
        ),
        migrations.AlterField(
            model_name='topologyinventory',
            name='inventory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Inventory'),
        ),
    ]
