# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_ui', '0004_auto_20180323_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='topologyinventory',
            old_name='inventory_id',
            new_name='inventory',
        ),
    ]
